### ISSUE TITLE
Fix mime type failures

### ISSUE THREAD

**Issue by tagliala** [ifad/colore#22]
|spec|ci|docker|notes|
|:-|:-:|:-:|:-|
|convert to MS from OO spreadsheet| ❌  | ✅  |libreoffice v5.1.6.2 / docker v6.1.5.2|
|convert to OO from MS word|❌ |❌||
|convert to OO from MS spreadsheet|❌ |❌||
|converts a tiff to HOCR|  ✅  |❌|ci teseract v3 / docker tesseract v4|
|ooffice runs|❌|❌ |ci libreoffice v5 / docker libreoffice v6|

```
Pending: (Failures listed here are expected and do not affect your suite's status)
  1) Heathen::Processor#libreoffice convert to MS from OO spreadsheet
     # check mime types
     Failure/Error: expect(@job.content.mime_type).to eq 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=binary'
     
       expected: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=binary"
            got: "application/octet-stream; charset=binary"
     
       (compared using ==)
     # ./spec/heathen/processor_methods/libreoffice_spec.rb:64:in `block (4 levels) in <top (required)>'
  2) Heathen::Processor#libreoffice convert to OO from MS word
     # check mime types
     Failure/Error: expect(oo_mime_types).to include(@job.content.mime_type)
       expected ["application/xml; charset=us-ascii", "application/octet-stream; charset=binary"] to include "application/vnd.oasis.opendocument.text; charset=binary"
     # ./spec/heathen/processor_methods/libreoffice_spec.rb:78:in `block (4 levels) in <top (required)>'
  3) Heathen::Processor#libreoffice convert to OO from MS spreadsheet
     # check mime types
     Failure/Error: expect(oo_mime_types).to include(@job.content.mime_type)
       expected ["application/xml; charset=us-ascii", "application/octet-stream; charset=binary"] to include "application/vnd.oasis.opendocument.spreadsheet; charset=binary"
     # ./spec/heathen/processor_methods/libreoffice_spec.rb:84:in `block (4 levels) in <top (required)>'
  4) Standard Heathen tasks: ooffice runs
     # check mime types
     Failure/Error: expect(oo_mime_types).to include(new_content.mime_type)
       expected ["application/xml; charset=us-ascii", "application/octet-stream; charset=binary"] to include "application/vnd.oasis.opendocument.text; charset=binary"
     # ./spec/integration/standard_tasks_spec.rb:102:in `block (3 levels) in <top (required)>'
```

```
$ convert --version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-09-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

$ libreoffice --version
LibreOffice 5.1.6.2 10m0(Build:2)

$ tesseract --version
tesseract 3.04.01
 leptonica-1.73
  libgif 5.1.2 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.1.2
before_install.13

$ tika --version
Apr 03, 2020 4:04:45 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
Apr 03, 2020 4:04:45 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: Tesseract OCR is installed and will be automatically applied to image files unless
you've excluded the TesseractOCRParser from the default parser.
Tesseract may dramatically slow down content extraction (TIKA-2359).
As of Tika 1.15 (and prior versions), Tesseract is automatically called.
In future versions of Tika, users may need to turn the TesseractOCRParser on via TikaConfig.
Apr 03, 2020 4:04:45 PM org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
Apache Tika 1.24

$ wkhtmltopdf --version
wkhtmltopdf 0.12.5 (with patched qt)
```

**Comment by tagliala** [comment]
Getting different failures in docker

```
rspec ./spec/heathen/processor_methods/libreoffice_spec.rb:73 # Heathen::Processor#libreoffice convert to OO from MS word
rspec ./spec/heathen/processor_methods/libreoffice_spec.rb:78 # Heathen::Processor#libreoffice convert to OO from MS spreadsheet
rspec ./spec/heathen/processor_methods/tesseract_spec.rb:21 # Heathen::Processor#tesseract converts a tiff to HOCR
rspec ./spec/integration/standard_tasks_spec.rb:98 # Standard Heathen tasks: ooffice runs
```
